plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

packageExtensions:
  recharts@*:
    peerDependencies:
      prop-types: ^15.8.1